version: '2'
services:
  app:
    build: .
    ports:
      - 80:80
    volumes:
      - ${APP_DIR}:/var/www/default

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
