
# Stripe lib uses the following
# - php7.1-curl
# - php7.1-mbstring

- name: Add ppa:ondrej/php for 7.1
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  apt: name={{ item }}
  with_items:
    - php7.1-fpm
    - php7.1-cli
    - php7.1-xml
    # Laravel requires the following
    - php7.1-opcache
    - php7.1-pdo
    - php7.1-xml
    - php7.1-bcmath
    - php7.1-calendar
    - php7.1-ctype
    - php7.1-curl
    - php7.1-dom
    - php7.1-exif
    - php7.1-fileinfo
    - php7.1-ftp
    - php7.1-gd
    - php7.1-gettext
    - php7.1-iconv
    - php7.1-imap
    - php7.1-intl
    - php7.1-json
    - php7.1-mbstring
    - php7.1-mysqli
    - php7.1-pgsql
    - php7.1-phar
    - php7.1-posix
    - php7.1-readline
    - php7.1-shmop
    - php7.1-simplexml
    - php7.1-soap
    - php7.1-sockets
    - php7.1-sqlite3
    - php7.1-sysvmsg
    - php7.1-sysvsem
    - php7.1-sysvshm
    - php7.1-tokenizer
    - php7.1-wddx
    - php7.1-xmlreader
    - php7.1-xmlwriter
    - php7.1-xsl
    - php7.1-zip
    - composer

