- name: Add ppa:ondrej/php for 7.x
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php{{ php.version }}-fpm
    - php{{ php.version }}-cli
    - php{{ php.version }}-xml
    - php{{ php.version }}-opcache
    - php{{ php.version }}-pdo
    - php{{ php.version }}-xml
    - php{{ php.version }}-bcmath
    - php{{ php.version }}-calendar
    - php{{ php.version }}-ctype
    - php{{ php.version }}-curl
    - php{{ php.version }}-dom
    - php{{ php.version }}-exif
    - php{{ php.version }}-fileinfo
    - php{{ php.version }}-ftp
    - php{{ php.version }}-gd
    - php{{ php.version }}-gettext
    - php{{ php.version }}-iconv
    - php{{ php.version }}-imap
    - php{{ php.version }}-intl
    - php{{ php.version }}-json
    - php{{ php.version }}-mbstring
    - php{{ php.version }}-mysqli
    - php{{ php.version }}-pgsql
    - php{{ php.version }}-phar
    - php{{ php.version }}-posix
    - php{{ php.version }}-readline
    - php{{ php.version }}-shmop
    - php{{ php.version }}-simplexml
    - php{{ php.version }}-soap
    - php{{ php.version }}-sockets
    - php{{ php.version }}-sqlite3
    - php{{ php.version }}-sysvmsg
    - php{{ php.version }}-sysvsem
    - php{{ php.version }}-sysvshm
    - php{{ php.version }}-tokenizer
    - php{{ php.version }}-wddx
    - php{{ php.version }}-xmlreader
    - php{{ php.version }}-xmlwriter
    - php{{ php.version }}-xsl
    - php{{ php.version }}-zip
    - composer

- name: error_log to stderr
  ini_file:
    dest: /etc/php/{{ php.version }}/fpm/php.ini
    section: PHP
    option: error_log
    value: "/proc/1/fd/2"
    backup: yes
  notify:
    - php-fpm restart

- name: clear_env=no on php-fpm workers
  ini_file:
    dest: /etc/php/{{ php.version }}/fpm/pool.d/www.conf
    section: www
    option: clear_env
    value: "no"
    backup: yes
  notify:
    - php-fpm restart

- name: link init.d php-fpm to php{{ php.version }}-fpm
  file:
    dest: /etc/init.d/php-fpm
    src: /etc/init.d/php{{ php.version }}-fpm
    state: link

- name: link php-fpm to php{{ php.version }}-fpm
  alternatives:
    link: /usr/sbin/php-fpm
    name: php-fpm
    path: /usr/sbin/php-fpm{{ php.version }}
    priority: 1

