
# Stripe lib uses the following
# - php7.0-curl
# - php7.0-mbstring

- name: Install php
  apt: name={{ item }}
  with_items:
    - php7.0-cli
    - php7.0-xml
    # Laravel requires the following
    - php7.0-opcache
    - php7.0-pdo
    - php7.0-xml
    - php7.0-bcmath
    - php7.0-calendar
    - php7.0-ctype
    - php7.0-curl
    - php7.0-dom
    - php7.0-exif
    - php7.0-fileinfo
    - php7.0-ftp
    - php7.0-gd
    - php7.0-gettext
    - php7.0-iconv
    - php7.0-imap
    - php7.0-intl
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mysqli
    - php7.0-pgsql
    - php7.0-phar
    - php7.0-posix
    - php7.0-readline
    - php7.0-shmop
    - php7.0-simplexml
    - php7.0-soap
    - php7.0-sockets
    - php7.0-sqlite3
    - php7.0-sysvmsg
    - php7.0-sysvsem
    - php7.0-sysvshm
    - php7.0-tokenizer
    - php7.0-wddx
    - php7.0-xmlreader
    - php7.0-xmlwriter
    - php7.0-xsl
    - php7.0-zip
    - composer

