
# Stripe lib uses the following
# - php7.2-curl
# - php7.2-mbstring

- name: Add ppa:ondrej/php for 7.1/7.2
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  apt: name={{ item }}
  with_items:
    - php7.2-fpm
    - php7.2-cli
    - php7.2-xml
    # Laravel requires the following
    - php7.2-opcache
    - php7.2-pdo
    - php7.2-xml
    - php7.2-bcmath
    - php7.2-calendar
    - php7.2-ctype
    - php7.2-curl
    - php7.2-dom
    - php7.2-exif
    - php7.2-fileinfo
    - php7.2-ftp
    - php7.2-gd
    - php7.2-gettext
    - php7.2-iconv
    - php7.2-imap
    - php7.2-intl
    - php7.2-json
    - php7.2-mbstring
    - php7.2-mysqli
    - php7.2-pgsql
    - php7.2-phar
    - php7.2-posix
    - php7.2-readline
    - php7.2-shmop
    - php7.2-simplexml
    - php7.2-soap
    - php7.2-sockets
    - php7.2-sqlite3
    - php7.2-sysvmsg
    - php7.2-sysvsem
    - php7.2-sysvshm
    - php7.2-tokenizer
    - php7.2-wddx
    - php7.2-xmlreader
    - php7.2-xmlwriter
    - php7.2-xsl
    - php7.2-zip
    - composer

- name: clear_env=no on php-fpm workers
  ini_file:
    path: /etc/php/7.2/fpm/pool.d/www.conf
    section: www
    option: clear_env
    value: no
    backup: yes

